#!/bin/sh
#
# Xcode Cloud post-clone script for this Flutter app.
#
# Xcode Cloud runs this after cloning the repository but BEFORE xcodebuild.
# This is required because the Xcode project depends on several files that are
# generated by Flutter and are NOT committed to git:
#
#   - ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage
#     (the Swift Package Manager package referenced by Runner.xcodeproj —
#      without it xcodebuild fails with
#      "Could not resolve package dependencies: ... doesn't exist in file system")
#   - ios/Flutter/Generated.xcconfig
#   - ios/.symlinks
#   - ios/Pods            (CocoaPods dependencies)
#
# We generate them here, before xcodebuild tries to resolve them.
set -e

FLUTTER_CHANNEL="stable"

# ---------------------------------------------------------------------------
# 1. Install / locate the Flutter SDK.
# ---------------------------------------------------------------------------
FLUTTER_SDK="$HOME/flutter"

if [ ! -x "$FLUTTER_SDK/bin/flutter" ]; then
  echo "==> Cloning Flutter SDK ($FLUTTER_CHANNEL)..."
  git clone --depth 1 \
    --branch "$FLUTTER_CHANNEL" \
    https://github.com/flutter/flutter.git \
    "$FLUTTER_SDK"
else
  echo "==> Flutter SDK already present at $FLUTTER_SDK"
fi

export PATH="$FLUTTER_SDK/bin:$PATH"

flutter config --no-analytics >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# 2. Generate the Flutter artifacts required by the Xcode project.
#    `flutter pub get` generates:
#      - ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage
#      - ios/Flutter/Generated.xcconfig
#      - ios/.symlinks
# ---------------------------------------------------------------------------
echo "==> flutter pub get..."
flutter pub get

# ---------------------------------------------------------------------------
# 3. Install CocoaPods dependencies (ios/Pods).
# ---------------------------------------------------------------------------
if ! command -v pod >/dev/null 2>&1; then
  echo "==> CocoaPods not found, installing..."
  gem install cocoapods --no-document
fi

echo "==> pod install..."
(
  cd ios
  pod install
)

echo "==> Xcode Cloud post-clone setup complete."
