#!/bin/sh
#
# Xcode Cloud post-clone script for this Flutter app.
#
# Xcode Cloud runs this after cloning the repository but BEFORE xcodebuild.
# This is required because the Xcode project depends on several files that are
# generated by Flutter and are NOT committed to git:
#
#   - ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage
#     (the Swift Package Manager package referenced by Runner.xcodeproj —
#      without it xcodebuild fails with
#      "Could not resolve package dependencies: ... doesn't exist in file system")
#   - ios/Flutter/Generated.xcconfig
#   - ios/.symlinks
#   - ios/Pods            (CocoaPods dependencies)
#
# Every line prints a marker so you can confirm in the Xcode Cloud logs that
# this script actually ran and that the required package was generated.
set -e

echo "=== [ci_post_clone] start: $(pwd) user=$(whoami) ==="

FLUTTER_CHANNEL="${FLUTTER_CHANNEL:-stable}"
FLUTTER_SDK="$HOME/flutter"

# ---------------------------------------------------------------------------
# 1. Install / locate the Flutter SDK.
# ---------------------------------------------------------------------------
if [ ! -x "$FLUTTER_SDK/bin/flutter" ]; then
  echo "=== [ci_post_clone] cloning Flutter SDK ($FLUTTER_CHANNEL) -> $FLUTTER_SDK ==="
  rm -rf "$FLUTTER_SDK"
  git clone --depth 1 --branch "$FLUTTER_CHANNEL" \
    https://github.com/flutter/flutter.git \
    "$FLUTTER_SDK"
else
  echo "=== [ci_post_clone] Flutter SDK already present at $FLUTTER_SDK ==="
fi

export PATH="$FLUTTER_SDK/bin:$PATH"

echo "=== [ci_post_clone] flutter version ==="
flutter --version

# Make sure Swift Package Manager is enabled so `flutter pub get` emits the
# FlutterGeneratedPluginSwiftPackage directory that the Xcode project needs.
flutter config --enable-swift-package-manager

# ---------------------------------------------------------------------------
# 2. Generate Flutter artifacts (SPM package, Generated.xcconfig, .symlinks).
# ---------------------------------------------------------------------------
echo "=== [ci_post_clone] flutter pub get ==="
flutter pub get

echo "=== [ci_post_clone] verifying generated SPM package ==="
if [ -d "ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage" ]; then
  echo "OK: ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage present"
  ls -la ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage/
else
  echo "ERROR: FlutterGeneratedPluginSwiftPackage was NOT generated"
  echo "ls ios/Flutter/ephemeral:"
  ls -la ios/Flutter/ephemeral 2>&1 || true
  exit 1
fi

# ---------------------------------------------------------------------------
# 3. Install CocoaPods dependencies (ios/Pods).
# ---------------------------------------------------------------------------
if ! command -v pod >/dev/null 2>&1; then
  echo "=== [ci_post_clone] CocoaPods not found, installing... ==="
  gem install cocoapods --no-document
fi

echo "=== [ci_post_clone] pod install ==="
(
  cd ios
  pod install
)

echo "=== [ci_post_clone] complete ==="
